// This file was generated by ts-rs. Do not edit this file manually.

export interface Position { x: number, y: number, }
export interface GridSize { width: number, height: number, }
export type Direction = "North" | "South" | "East" | "West";
export type CellType = "Empty" | "SnakeHead" | "SnakeBody" | "Food" | "Obstacle" | "Exit";
export type GameStatus = "Playing" | "GameOver" | "LevelComplete" | "AllComplete";
export interface Snake { segments: Array<Position>, direction: Direction | null, }
export interface LevelDefinition { id: number, name: string, gridSize: GridSize, snake: Array<Position>, obstacles: Array<Position>, food: Array<Position>, exit: Position, snakeDirection: Direction | null, }
export interface GameState { status: GameStatus, currentLevel: number, moves: number, foodCollected: number, totalFood: number, }
export interface Frame { grid: Array<Array<CellType>>, state: GameState, snake: Snake, }
